Add H128 type
paritytech/parity-common pull request #434
Opened 2020-10-23 19:11 UTC by drewstone

2020-10-23 19:42 UTC, dvdplm requested changes
A motivation would be good, why do we need this?

2020-10-23 19:42 UTC, dvdplm commented on primitive-types/src/lib.rs
> +	/// Fixed-size uninterpreted hash type with 20 bytes (160 bits) size.
fix docs please

2020-10-27 20:00 UTC, drewstone commented
I'm working on an ETH light-client built off of rainbow bridge and these types are useful.

2020-10-27 20:07 UTC, ordian approved these changes

2020-10-27 21:40 UTC, dvdplm approved these changes

2020-10-27 22:16 UTC, merged