Remove U64 and U128
paritytech/parity-common pull request #473
Opened 2020-12-07 13:50 UTC by vorot93

Obsoleted by `u64` and `u128` in Rust standard library.

2020-12-07 14:14 UTC, ordian commented
My assumption is that these types are used to enforce some serialization format for RPC requests. Maybe this is easy to work around, but maybe there are also some use-cases I'm missing.

2020-12-07 15:21 UTC, niklasad1 requested changes
> My assumption is that these types are used to enforce some serialization format for RPC requests. Maybe this is easy to work around, but maybe there are also some use-cases I'm missing.

Yes, these types exist because integer deserialization in ethereum is different because they are prefixed by `0x` and won't work with the built-in types (u64/u128) in the Rust standard library without "glue code" (parsing hex strings doesn't work without removing the hex prefix in Rust and special handling of leading zeros and similar)

So this won't work

2020-12-09 02:29 UTC, sorpaas commented
It's right now in Frontier for some borrowed code from OE, but I'm in favor of removing those -- should be easy to change them to the raw type.

2020-12-09 02:29 UTC, sorpaas approved these changes

2020-12-09 02:31 UTC, sorpaas commented
> My assumption is that these types are used to enforce some serialization format for RPC requests. Maybe this is easy to work around, but maybe there are also some use-cases I'm missing.

Yeah but I don't like that design to be honest. It's much better to define a type `HexDisplay` and use that for RPC return values.

2020-12-09 10:34 UTC, ordian commented
> > My assumption is that these types are used to enforce some serialization format for RPC requests. Maybe this is easy to work around, but maybe there are also some use-cases I'm missing.
> 
> Yeah but I don't like that design to be honest. It's much better to define a type `HexDisplay` and use that for RPC return values.

Yeah, I don't mind removing them, but we should provide `HexDisplay` as a migration path. Not sure if it would fit `primitive-types` or `ethereum-types` though.

2020-12-25 21:04 UTC, ordian commented
Planning to publish a few crates including uint 0.9 after #486 is merged.
As I mentioned I don't mind merging this PR as long as we provide a migration path (`HexDisplay` or whatever).

2020-12-30 20:49 UTC, vorot93 commented
@ordian My focus has switched from web3 JSONRPC to binary typed RPC protocols (like gRPC), so I have much less need and bandwidth to push this PR over the finish line. I suggest making a new release without it.

2022-02-04 09:50 UTC, closed without merging