add `H384` and `H768` hash types
paritytech/parity-common pull request #684
Opened 2022-10-18 12:21 UTC by drskalman

These hash types are needed to be able to hash to the base fields of group G1 and G2 of  BLS12-377 and BLS12-381 curves. BLS12-377 is going to be used in BEEFY Messages for the ultra light client.

2022-10-18 12:27 UTC, acatangiu approved these changes
LGTM!

2022-10-18 12:37 UTC, svyatonik approved these changes
Don't know much about BLS12-377, but code changes LGTM

2022-10-18 12:43 UTC, ordian requested changes
Missing impls for ~~`num-traits`,~~  `impl-serde`, `impl-codec`, `impl-rlp` ~~as well as convertions from other smaller types and to larger types (see the file below)~~.

2022-10-27 09:01 UTC, ordian approved these changes

2022-10-27 09:37 UTC, merged